# Generated by Django 5.1.1 on 2024-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_control', '0002_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=255, upload_to='videos/'),
        ),
    ]
