# Generated by Django 5.1.1 on 2024-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_control', '0003_alter_photo_name_alter_video_title_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
