# Generated by Django 5.1.1 on 2024-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_control', '0004_photo_photo_height_photo_photo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='resized_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resized_photos/'),
        ),
    ]
